name: CI-CD-pipeline-to-AWS
env :
  El_Package_S3    : "mykhailo-app-package"
  Eb_App_Name      : "My_APP"
  Eb_Enviroment_Var: "My_App-env"
  Deploy_package_na: "my_app_${{ github.sha }}.zip"
  Aws_Region_Name  : "eu-central-1"
on :
 push:
   branches: 
       - main
jobs: 
 my_ci:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    - name: Create Zip deployment package
      run : zip -r ${{ env.Deploy_package_na }} ./ -x *.git*
      
    - name: Conf AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id       : ${{ secrets.AWS_ACCESS_KEYS }}
        aws-secret-access-key   : ${{ secrets.AWS_SECRET_KEY }}
        aws-region              : ${{ env.Aws_Region_Name }}
        
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.Deploy_package_na }} s3://${{ env.El_Package_S3 }}/  
        
    - name: Print Happy Deploy finish
      run : echo "CI Pipeline part Finished successfully!"
      
     
