name: CI-CD-pipeline-to-AWS
env :
  El_Package_S3    : "mykhailok"
  Eb_App_Name      : "Mybeanstalk"
  Eb_Enviroment_Var: "Mybeanstalk-env"
  Deploy_package_na: "my_app_${{ github.sha }}.zip"
  Aws_Region_Name  : "eu-central-1"
on :
 push:
   branches: 
       - main
jobs: 
 my_ci:
    runs-on: ubuntu-latest
    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
    - name: Create Zip deployment package
      run : zip -r ${{ env.Deploy_package_na }} ./ -x *.git*
      
    - name: Conf AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id       : ${{ secrets.AWS_ACCESS_KEYS }}
        aws-secret-access-key   : ${{ secrets.AWS_SECRET_KEY }}
        aws-region              : ${{ env.Aws_Region_Name }}
        
    - name: Copy Deployment package to S3 bucket
      run : aws s3 cp ${{ env.Deploy_package_na }} s3://${{ env.El_Package_S3 }}/  
        
    - name: Print Happy Deploy finish
      run : echo "CI Pipeline part Finished successfully!"
      
 my_cd_part:
   runs-on: ubuntu-latest
   needs: [my_ci]
   
   steps:
    - name: Conf AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id       : ${{ secrets.AWS_ACCESS_KEYS }}
        aws-secret-access-key   : ${{ secrets.AWS_SECRET_KEY }}
        aws-region              : ${{ env.Aws_Region_Name }}
        
    - name:  Create new ElastickBeanstalk App
      run : |
       aws elasticbeanstalk create-application-version \
       --application-name ${{ env.Eb_App_Name }} \
       --source-bundle S3Bucket="${{ env.El_Package_S3 }}",S3Key="${{ env.Deploy_package_na }}" \
       --version-label "Ver-${{ github.sha }}" \
       --description "CoimmitSHA-${{ github.sha }}" 
        
    - name: Deploy new ElasticBeanstalk Application Version
      run : aws elasticbeanstalk update-environment --environment-name ${{ env.Eb_Enviroment_Var }} --version-label "Ver-${{ github.sha }}"
      
    - name: Print Happy Message for CD finish
      run : echo "CD Pipeline part Finished successfully!" 
     
